// <auto-generated />
namespace LTTHver2._2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new46 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new46));
        
        string IMigrationMetadata.Id
        {
            get { return "202206040253009_new46"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
